### ISSUE TITLE
SDNext Support

### ISSUE THREAD

**Issue by Aptronymist** [chengzeyi/stable-fast#31]
Hi @chengzeyi, I sent an email to you last week but I wanted to try again, we'd love to get in touch with you since Vlad has now applied your code to SDNext, we're seeing great results on our dev branch.
Hit us up on our [discord server](https://discord.gg/VjvR2tabEX) or just reply to my email so we can connect, as we plan on posting our results.

Thanks!

**Comment by chengzeyi** [comment]
> Hi @chengzeyi, I sent an email to you last week but I wanted to try again, we'd love to get in touch with you since Vlad has now applied your code to SDNext, we're seeing great results on our dev branch.
> 
> Hit us up on our [discord server](https://discord.gg/VjvR2tabEX) or just reply to my email so we can connect, as we plan on posting our results.
> 
> 
> 
> Thanks!

Hey, @Aptronymist 

Thanks for your great work!
I have read your email but just didn't have time to respond to it quickly. Because I am too busy refactoring this project and building CI to release binary wheels these days🤣. You and your guys are really awesome and I will help in this as soon as I have time. I have many new features which are super useful for users like dynamically switching LoRA. Let's work together to bring them to SD Next!😆

**Comment by chengzeyi** [comment]
@Aptronymist Just let me know if there is anything that I could help with! I am trying to create a stable interface and installation process for other projects to better integrate with this.

**Comment by vladmandic** [comment]
FYI, stable-fast integration code in sd.next is at https://github.com/vladmandic/automatic/blob/f3aa5ade133db0f86b6234aad7943784378e3ddb/modules/sd_models_compile.py#L50

if you have further suggestions, let me know!
re: dynamically switch lora - interesting! that has always been one of biggest issues with any torch compile approach.

**Comment by Aptronymist** [comment]
Sorry for missing these, I really don't check my own email much, and these notifications that many times a day, but I'm glad you came to our discord anyway, should make things a lot easier!
