### ISSUE TITLE
Stable Video Optimizations?

### ISSUE THREAD

**Issue by rbhuta** [chengzeyi/stable-fast#67]
Do you think any of these optimizations could be applied to Stable Video Diffusion? I'd like to help here if possible.

**Comment by chengzeyi** [comment]
> Do you think any of these optimizations could be applied to Stable Video Diffusion? I'd like to help here if possible.

It should work. But I haven't started testing it. It would be better if you can experiment at first and contribute an example case in `examples` dir😊.

**Comment by Davin05** [comment]
> > Do you think any of these optimizations could be applied to Stable Video Diffusion? I'd like to help here if possible.
> 
> It should work. But I haven't started testing it. It would be better if you can experiment at first and contribute an example case in `examples` dir😊.

@chengzeyi Hi, thanks for this repo! I saw `compile` in `stable_diffusion_pipeline_compiler` now has a comment about SVD. I am wondering how to use apply Stable Fast  on SVD models. Because from the official examples, they are using DiffusionEngine, which has an attribute model which is an OpenAIWrapper which has an attribute diffusion model which is a VideoUnet class.  I tried directly do `compile_unet` on VideoUnet, but it didnt work. How do you correctly do the compile. Thanks so much!

**Comment by chengzeyi** [comment]
StableVideoDiffusionPipeline is now officially supported.
